# make a dependency when kdp is published
presto:
  url: "http://kdp-kubernetes-data-platform-presto.kdp:8080"

redis:
  host: carpenter-redis-master

image:
  repository: smartcitiesdata/carpenter
  tag: development
  pullPolicy: IfNotPresent

# defaults to be overridden by user
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
