presto:
  user: "estuary"
  url: "http://kdp-kubernetes-data-platform-presto.kdp:8080"
  schema_name: event_stream
  table_name: history

kafka:
  #comma delimited list of kafka seed brokers
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

estuary:
  data_topic: event-stream
  dlq_topic: streaming-dead-letters

image:
  repository: smartcitiesdata/estuary
  tag: development
  pullPolicy: Always

# defaults to be overridden by user
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
