apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-ui
  template:
    metadata:
      labels:
        app: discovery-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: discovery-ui
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
          - name: "API_HOST"
            value: {{ .Values.env.api_host }}
          - name: "GTM_ID"
            value: {{ .Values.env.gtm_id }}
          - name: "BASE_URL"
            value: {{ .Values.env.base_url }}
          - name: "STREETS_TILE_LAYER_URL"
            value: {{ .Values.env.streets_tile_layer_url }}
          - name: "LOGO_URL"
            value: {{ .Values.env.logo_url | default "null" }}
