redis:
  fullnameOverride: redis
  usePassword: false
  cluster:
    enabled: false
openldap:
  fullnameOverride: ldap-openldap
  enabled: true
  adminPassword: ''
  env:
    LDAP_BASE_DN: dc=example,dc=org
  customLdifFiles:
    init.ldif : |
      dn: ou=orgs,dc=example,dc=org
      objectClass: top
      objectClass: organizationalUnit
      ou: orgs
andi:
  enabled: true
  image:
    tag: 0.6.0
  redis:
    host: redis-master
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
  service:
    type: ClusterIP
discovery-api:
  image:
    tag: 0.16.2
  redis:
    host: redis-master
  presto:
    url: http://kdp-kubernetes-data-platform-presto:8080
  postgres:
    host: ''
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
  s3:
    hostedFileBucket: hosted-bucket
  ldap:
    host: ldap-openldap
    base: "dc=example,dc=org"
  vault:
    endpoint: ""
  environment: demo
  service:
    type: LoadBalancer
discovery-streams:
  enabled: false
  image:
    environment: demo
    tag: 0.12.4
  service:
    type: LoadBalancer
kubernetes-data-platform:
  fullnameOverride: kdp
  enabled: false
  global:
    environment: demo
    objectStore:
      bucketName: ''
      accessKey: ''
      accessSecret: ''
    ingress:
      annotations: {}
  presto:
    workers: 2
    ingress:
      enable: false
      annotations: {}
    jvm:
      maxHeapSize: 1536M
    deploy:
      container:
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
  minio:
    enable: true
    azure:
      enable: false
  postgres:
    enable: true
    service:
      externalAddress: ''
    db:
      name: metastore
      user: ''
      password: ''
  metastore:
    allowDropTable: true
    timeout: 360m
forklift:
  fullnameOverride: forklift
  enabled: true
  image:
    tag: 0.9.0
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  kdp:
    url: "http://kdp-kubernetes-data-platform-presto:8080"
  redis:
    host: redis-master
  prometheus:
    scrape: false
reaper:
  fullnameOverride: reaper
  enabled: true
  image:
    tag: 0.10.1
  redis:
    host: redis-master
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
  vault:
    endpoint: ""
valkyrie:
  fullnameOverride: valkyrie
  enabled: true
  replicaCount: 1
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  redis:
    host: redis-master
flair:
  enabled: true
  redis:
    host: redis-master
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
odo:
  enabled: true
