vault:
  port: 8200
  clusterPort: 8201
  repository: vault
  tag: 1.3.1
  pullPolicy: IfNotPresent
  volumeSize: 5Gi
  secretsPath: secrets/smart_city
  # Optional storage class
  # storageClassName: encrypted-example
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  config:
    listener:
      tcp:
        address: '[::]:8200'
        cluster_address: '[::]:8201'
        tls_disable: true
        tls_prefer_server_cipher_suites: true
        tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
    storage:
      file:
        path: "/keys"
  roles:
    - name: discovery-api-role
      boundServiceAccounts: discovery-api
      boundServiceAccountNamespaces: discovery
      policies: discovery_api_aws
      tokenTtl: 2m
    - name: reaper-role
      boundServiceAccounts: reaper
      boundServiceAccountNamespaces: streaming-services
      policies: reaper_aws,dataset_access_keys
      tokenTtl: 2m
    - name: odo-role
      boundServiceAccounts: odo
      boundServiceAccountNamespaces: streaming-services
      policies: odo_aws
    - name: andi-role
      boundServiceAccounts: andi
      boundServiceAccountNamespaces: admin
      policies: dataset_access_keys, andi_write_only
      tokenTtl: 2m

  policies:
    - name: dataset_access_keys
      path: secrets/smart_city/ingestion/*
      capabilities: '["read", "list"]'
    - name: reaper_aws
      path: secrets/smart_city/aws_keys/reaper
      capabilities: '["read", "list"]'
    - name: odo_aws
      path: secrets/smart_city/aws_keys/odo
      capabilities: '["read", "list"]'
    - name: discovery_api_aws
      path: secrets/smart_city/aws_keys/discovery_api
      capabilities: '["read", "list"]'
    - name: andi_write_only
      path: secrets/smart_city/ingestion/*
      capabilities: '["create", "update"]'

kubectl:
  version: "1.14.0"

jq:
  version: "1.6"

ldap:
  server: ""
