
kafka:
  #comma delimited list of kafka seed brokers
  pipeline_brokers: incoming-data-broker
  strimziCluster: strimzi-cluster
  transformed_topic: topic-to-read-from
  public_brokers: public-kafka-cluster-broker

redis:
  host: streisand-redis-master

image:
  repository: smartcitiesdata/streisand
  tag: development
  pullPolicy: Always

# defaults to be overridden by user
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
